auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: sw55555's blog
url: https://sw55555.github.io
feed: /atom.xml
author_info: <a href="https://sw55555.github.io/">sw55555</a>
